from tkinter import*

wind=Tk()

Label(text=" ").grid(row=0,column=0)
Label(text="0\n7.40-8.25",borderwidth=1,relief="solid").grid(row=0,column=2,sticky=W+E+N+S)
Label(text="1\n8.30-9.15",borderwidth=1,relief="solid").grid(row=0,column=3,sticky=W+E+N+S)
Label(text="2\n9.20-10.05",borderwidth=1,relief="solid").grid(row=0,column=4,sticky=W+E+N+S)
Label(text="3\n10.10-10.55",borderwidth=1,relief="solid").grid(row=0,column=5,sticky=W+E+N+S)
Label(text="4\n11.00-11.45",borderwidth=1,relief="solid").grid(row=0,column=6,sticky=W+E+N+S)
Label(text="5\n11.50-12.35",borderwidth=1,relief="solid").grid(row=0,column=7,sticky=W+E+N+S)
Label(text="6\n12.40-13.25",borderwidth=1,relief="solid").grid(row=0,column=8,sticky=W+E+N+S)
Label(text="7\n13.30-14.15",borderwidth=1,relief="solid").grid(row=0,column=9,sticky=W+E+N+S)
Label(text="8\n14.20-15.05",borderwidth=1,relief="solid").grid(row=0,column=10,sticky=W+E+N+S)
Label(text="9\n15.10-15.55",borderwidth=1,relief="solid").grid(row=0,column=11,sticky=W+E+N+S)
Label(text="10\n16.00-16.45",borderwidth=1,relief="solid").grid(row=0,column=12,sticky=W+E+N+S)

esm=Label(text="Esmaspäev",borderwidth=1,relief="solid").grid(row=1,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
teis=Label(text="Teisipäev",borderwidth=1,relief="solid").grid(row=3,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
kolm=Label(text="Kolmapäev",borderwidth=1,relief="solid").grid(row=5,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
nelj=Label(text="Neljapäev",borderwidth=1,relief="solid").grid(row=7,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)
reede=Label(text="Reede",borderwidth=1,relief="solid").grid(row=9,rowspan=2,column=0,columnspan=2,sticky=W+E+N+S)

Label(text=" ",borderwidth=1,relief="solid").grid(row=1,column=3,sticky=W+E+N+S)
esttug2=Button(text="Tugiõpe Eesti keel \n 1 grupp",bg="#9d7a73",borderwidth=1,relief="solid").grid(row=2,column=3,sticky=W+E+N+S)
esmLogist=Button(text="Logistikateenused ja \n varude juhtmine",bg="lightgreen",borderwidth=1,relief="solid").grid(row=1,rowspan=2,column=4,columnspan=2,sticky=W+E+N+S)
mat=Button(text="Matemaatika",bg="pink",borderwidth=1,relief="solid").grid(row=1,rowspan=2,column=6,columnspan=2,sticky=W+E+N+S)
Label(text=" Перерыв ",borderwidth=1,relief="solid").grid(row=1,rowspan=2,column=8,sticky=W+E+N+S)
keel=Button(text="Keel ja kirjandus",bg="lightgreen",borderwidth=1,relief="solid").grid(row=1,rowspan=2,column=9,columnspan=2,sticky=W+E+N+S)
tugmat=Button(text="Tugiõpe Matemaatika",bg="pink",borderwidth=1,relief="solid").grid(row=1,rowspan=2,column=11,sticky=W+E+N+S)

Label(text=" ",borderwidth=1,relief="solid").grid(row=6,column=3,sticky=W+E+N+S)
tugkeem=Button(text="Tugiõpe Keemia",borderwidth=1,relief="solid").grid(row=3,rowspan=2,column=3,sticky=W+E+N+S)
teisprog=Button(text="Programmeerimise alused \n (eesti keeles)",bg="lightblue",borderwidth=1,relief="solid").grid(row=3,rowspan=2,column=4,columnspan=3,sticky=W+E+N+S)
Label(text=" Перерыв ",borderwidth=1,relief="solid").grid(row=3,rowspan=2,column=7,sticky=W+E+N+S)
fuusika=Button(text="Füüsika",bg="pink",borderwidth=1,relief="solid").grid(row=3,rowspan=2,column=8,columnspan=2,sticky=W+E+N+S)

esttug1=Button(text="Tugiõpe Eesti keel \n 2 grupp",borderwidth=1,relief="solid").grid(row=5,column=3,sticky=W+E+N+S)
kunst=Button(text="Kunstiained",borderwidth=1,relief="solid").grid(row=5,rowspan=2,column=4,columnspan=2,sticky=W+E+N+S)
Label(text=" Перерыв ",borderwidth=1,relief="solid").grid(row=5,rowspan=2,column=6,sticky=W+E+N+S)
kehalinekasv=Button(text="Kehaline Kasvatus",borderwidth=1,relief="solid").grid(row=5,rowspan=2,column=7,columnspan=2,sticky=W+E+N+S)

neljLogist=Button(text="Logistikateenused ja \n varude juhtmine",borderwidth=1,relief="solid").grid(row=7,rowspan=2,column=3,columnspan=2,sticky=W+E+N+S)
Label(text=" Перерыв ",borderwidth=1,relief="solid").grid(row=7,rowspan=2,column=5,sticky=W+E+N+S)
neljprog=Button(text="Programmeerimise alused \n (eesti keeles)",bg="lightblue",borderwidth=1,relief="solid").grid(row=7,rowspan=2,column=6,columnspan=2,sticky=W+E+N+S)
ingl1=Button(text="Inglise keel",borderwidth=1,relief="solid").grid(row=7,column=8,columnspan=2,sticky=W+E+N+S)
merk2=Button(text="Rakendustarkvara ja \n arenduskeskkonna \n loomine (IT valdkonna alusteadmised)",borderwidth=1,relief="solid").grid(row=8,column=8,columnspan=2,sticky=W+E+N+S)
merk1=Button(text="Rakendustarkvara ja \n arenduskeskkonna \n loomine (IT valdkonna alusteadmised)",borderwidth=1,relief="solid").grid(row=7,column=10,columnspan=2,sticky=W+E+N+S)
est2=Button(text="Eesti keel \n 2 grupp",borderwidth=1,relief="solid").grid(row=8,column=10,columnspan=2,sticky=W+E+N+S)
ruhm=Button(text="Rühmajuhataja \n tund",borderwidth=1,relief="solid").grid(row=7,rowspan=2,column=12,sticky=W+E+N+S)

est1=Button(text="Eesti keel \n 1 grupp",borderwidth=1,relief="solid").grid(row=9,column=3,columnspan=2,sticky=W+E+N+S)
merkul2=Button(text="Rakendustarkvara ja \n arenduskeskkonna \n loomine (IT valdkonna alusteadmised)",borderwidth=1,relief="solid").grid(row=10,column=3,columnspan=2,sticky=W+E+N+S)
redprogram=Button(text="Programmeerimise alused \n (eesti keeles)",bg="lightblue",borderwidth=1,relief="solid").grid(row=9,rowspan=2,column=5,columnspan=5,sticky=W+E+N+S)
merkul1=Button(text="Rakendustarkvara ja \n arenduskeskkonna \n loomine (IT valdkonna alusteadmised)",borderwidth=1,relief="solid").grid(row=9,column=10,columnspan=2,sticky=W+E+N+S)
ingl2=Button(text="inglise keel",borderwidth=1,relief="solid").grid(row=10,column=10,columnspan=2,sticky=W+E+N+S)

wind.mainloop()